# Generated by Django 5.2.8 on 2025-11-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=200)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.university')),
            ],
            options={
                'db_table': 'Majors',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('income_level', models.CharField(blank=True, choices=[('1분위', '1분위'), ('2분위', '2분위'), ('3분위', '3분위'), ('4분위', '4분위'), ('5분위', '5분위'), ('6분위', '6분위'), ('7분위', '7분위'), ('8분위', '8분위'), ('9분위', '9분위'), ('10분위', '10분위')], max_length=10, null=True)),
                ('receive_notifications', models.BooleanField(default=False)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.major')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
