# Generated by Django 5.0.6 on 2025-11-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gpa',
            field=models.CharField(max_length=10),
        ),
    ]
