# Generated by Django 5.2.8 on 2025-11-25 06:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mypage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_date', models.IntegerField(help_text='0 = D-day, 1 = D-1 ... 10 = D-10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('bookmark', models.ForeignKey(db_column='bookmark_id', on_delete=django.db.models.deletion.CASCADE, to='mypage.bookmark')),
            ],
            options={
                'db_table': 'Notifications',
                'unique_together': {('bookmark', 'notification_date')},
            },
        ),
    ]
